services:
  wyoming-parakeet:
    image: jpwoodbu/wyoming-parakeet:latest
    container_name: wyoming-parakeet
    restart: unless-stopped
    ports:
      - "10300:10300"
    user: "1000:1000"
    volumes:
      - models:/models

volumes:
  models:
